const fs = require('fs');
const path = require('path');
const { Octokit } = require('@octokit/rest');

// GITHUB_TOKEN env olarak workflow'da tanımlanmalı
const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

const OWNER = process.env.GITHUB_REPOSITORY?.split('/')[0];
const REPO = process.env.GITHUB_REPOSITORY?.split('/')[1];
const REPORT_PATH = path.join(__dirname, '../../test-results/playwright-report.json');

(async () => {
  if (!fs.existsSync(REPORT_PATH)) {
    console.error('JSON test raporu bulunamadı:', REPORT_PATH);
    process.exit(1);
  }

  const report = JSON.parse(fs.readFileSync(REPORT_PATH, 'utf-8'));

  const failedTests = report.suites
    .flatMap(suite => suite.specs)
    .flatMap(spec => spec.tests)
    .filter(test => test.results.some(result => result.status === 'failed'));

  if (failedTests.length === 0) {
    console.log('Hatalı test bulunamadı, issue açılmayacak.');
    return;
  }

  for (const test of failedTests) {
    const testTitle = test.title.join(' > ');
    const firstFailure = test.results.find(r => r.status === 'failed');
    const errorMsg = firstFailure?.error?.message || 'Bilinmeyen hata';
    const stack = firstFailure?.error?.stack || '';

    const issueTitle = `🔴 Test Failed: ${testTitle}`;
    const issueBody = `
### Hatalı Test: ${testTitle}

**Hata Mesajı:**
\`\`\`
${errorMsg}
\`\`\`

**Stack Trace:**
\`\`\`
${stack}
\`\`\`

Rapor: [HTML Raporu Görüntüle](${process.env.REPORT_URL})
`;

    // Aynı başlıkta açık issue varsa tekrar oluşturma
    const existingIssues = await octokit.rest.issues.listForRepo({
      owner: OWNER,
      repo: REPO,
      state: 'open',
      labels: 'automated-test',
    });

    const alreadyExists = existingIssues.data.some(issue => issue.title === issueTitle);
    if (alreadyExists) {
      console.log(`Issue zaten mevcut: ${issueTitle}`);
      continue;
    }

    // Yeni issue oluştur
    await octokit.rest.issues.create({
      owner: OWNER,
      repo: REPO,
      title: issueTitle,
      body: issueBody,
      labels: ['automated-test', 'bug'],
    });

    console.log(`Yeni issue oluşturuldu: ${issueTitle}`);
  }
})();
