name: Deploy Playwright Report to GitHub Pages

on:
  push:
    branches:
      - master  # Eğer ana dalın 'master' ise, 'main' değilse bunu düzelt

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repoyu checkout et
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # BURAYI 18 yaptık

      - name: Install dependencies
        run: npm ci  # Eğer package-lock.json varsa bu daha güvenli

      - name: Playwright browserları kur
        run: npx playwright install

      - name: Playwright testleri çalıştır
        run: npm test

      - name: GitHub Pages'a deploy et
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
