name: Deploy Playwright Test Report

on:
  workflow_run:
    workflows: ["Playwright Tests"]
    types:
      - completed

jobs:
  deploy-report:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-22.04      # burayı ubuntu-22.04 yaptım

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh -y

      - name: Retry downloading artifact until available
        run: |
          for i in {1..10}; do
            gh run download ${{ github.event.workflow_run.id }} --name playwright-report && exit 0
            echo "Artifact not found yet. Waiting 10 seconds..."
            sleep 10
          done
          echo "Artifact not found after 10 retries."
          exit 1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Deploy HTML report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: playwright-report
