name: Deploy Playwright Test Report

on:
  workflow_run:
    workflows: ["Playwright Tests"]
    types:
      - completed

jobs:
  deploy-report:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI (gh)
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Retry downloading artifact until available
        run: |
          for i in {1..10}; do
            echo "Attempt $i to download artifact..."
            rm -rf tmp-report playwright-report
            mkdir tmp-report
            if gh run download ${{ github.event.workflow_run.id }} --name playwright-report --dir tmp-report; then
              echo "Download successful."
              mv tmp-report/playwright-report ./playwright-report
              rm -rf tmp-report
              break
            else
              echo "Download failed or artifact not ready. Waiting 30 seconds..."
              sleep 30
            fi
          done

          if [ ! -d "playwright-report" ]; then
            echo "Artifact not found after 10 retries."
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Deploy HTML report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: playwright-report
