name: Deploy Report

on:
  workflow_run:
    workflows: ["Playwright Tests"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download Playwright HTML Report
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

<<<<<<< HEAD
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

=======
>>>>>>> 24cd45e (Revise deploy-report to always deploy reports)
      - name: Deploy HTML report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: playwright-report
