name: FOSSA Scan

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  fossa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run FOSSA Scan
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}

      - name: Download FOSSA Report
        run: |
          curl -H "Authorization: token ${{ secrets.FOSSA_API_KEY }}" \
          -s "https://app.fossa.com/api/revisions/${{ github.repository }}/latest" \
          -o fossa-report.json

      - name: Upload FOSSA Report
        uses: actions/upload-artifact@v4
        with:
          name: fossa-report
          path: fossa-report.json

      - name: Create Issues if Problems Found
        run: node .github/scripts/create-fossa-issues.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
