name: Run Playwright Tests and Publish Report

on:
  push:
    branches: [main]  # Ana dal覺n覺z覺n ad覺 (main veya master)

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run Playwright tests and generate HTML report
      run: npx playwright test --reporter=html

    - name: Copy report to docs folder
      run: |
        rm -rf docs/playwright-report
        mkdir -p docs/playwright-report
        cp -r playwright-report/* docs/playwright-report/

    - name: Commit and push report
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add docs/playwright-report
        git commit -m "Update Playwright HTML report" || echo "No changes to commit"
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
