<<<<<<< HEAD
name: Playwright Tests
=======
name: Run Playwright Tests
>>>>>>> 24cd45e (Revise deploy-report to always deploy reports)

on:
  push:
    branches:
      - master
  pull_request:
<<<<<<< HEAD
    branches:
      - master
=======
>>>>>>> 24cd45e (Revise deploy-report to always deploy reports)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
      - name: Checkout repo
=======
      - name: Checkout code
>>>>>>> 24cd45e (Revise deploy-report to always deploy reports)
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

<<<<<<< HEAD
      - name: Run Playwright tests and generate HTML + JSON reports
        run: |
          npx playwright test --reporter=json,html
          mkdir -p playwright-report
          mv playwright-report/report.html playwright-report/report.html || echo "No HTML report found"
          mv playwright-report/report.json playwright-report/report.json || echo "No JSON report found"
        continue-on-error: true   # testler hata verse bile devam et

      - name: Upload Playwright HTML report artifact
=======
      - name: Run Playwright tests and generate HTML + JSON report
        run: |
          npx playwright install
          npx playwright test --reporter=html,json

      - name: Upload Playwright HTML Report
        if: always()
>>>>>>> 24cd45e (Revise deploy-report to always deploy reports)
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
