name: Playwright Tests and Report to Jira

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    env:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      JIRA_PROJECT_KEY: EGT
      REPORT_URL: https://fatma-betul-ozdemir-mytech.github.io/docs/playwright-report/index.html

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test
        continue-on-error: true  # Testler başarısız olsa bile devam et

      - name: Generate Playwright HTML Report
        run: |
          mkdir -p playwright-report/html-report
          cp -r playwright-report/* playwright-report/html-report/

      - name: Deploy HTML Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report/html-report

      - name: Comment Test Results on Jira
        run: node jira-comment.js
