name: Security Scans

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  semgrep_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Semgrep
        run: npm install -g semgrep

      - name: Run Semgrep scan
        run: semgrep --config=auto --json > semgrep_report.json || true

      - name: Upload Semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep
          path: ./semgrep_report.json

  trivy_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update && sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.65.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.65.0_Linux-64bit.deb

      - name: Run Trivy scan
        run: trivy fs . --exit-code 0 --severity HIGH,CRITICAL --format table --output trivy_report.txt

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy
          path: ./trivy_report.txt

  nikto_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nikto
        run: sudo apt-get install nikto -y

      - name: Run Nikto scan
        run: nikto -h https://egundem.com -o nikto_report.txt

      - name: Upload Nikto report
        uses: actions/upload-artifact@v4
        with:
          name: nikto
          path: ./nikto_report.txt

  nuclei_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nuclei
        run: |
          curl -sL https://github.com/projectdiscovery/nuclei/releases/latest/download/nuclei_6.7.7_linux_64bit.zip -o nuclei.zip
          unzip nuclei.zip
          sudo mv nuclei /usr/local/bin/

      - name: Run Nuclei scan
        run: nuclei -u https://egundem.com -o nuclei_report.txt

      - name: Upload Nuclei report
        uses: actions/upload-artifact@v4
        with:
          name: nuclei
          path: ./nuclei_report.txt

  create_issues:
    runs-on: ubuntu-latest
    needs: [semgrep_scan, trivy_scan, nikto_scan, nuclei_scan]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create issues from security reports
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_ISSUE_CREATION }}
          REPORT_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: node .github/scripts/create-issues-security.cjs
