name: Trivy Güvenlik Taraması

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy (latest)
        run: |
          sudo apt-get update
          sudo apt-get install wget -y
          wget https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh
          sudo sh install.sh

      - name: Run Trivy filesystem scan
        run: |
          trivy fs . --exit-code 0 --severity HIGH,CRITICAL --format table --output trivy_report.txt

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy_report.txt
