name: Security All Scans

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  security_scans:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Semgrep
      - name: Run Semgrep Scan
        uses: returntocorp/semgrep-action@v3
        with:
          config: "p/ci"
          output: semgrep_report.json
          format: json

      - name: Upload Semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep_report.json

      # Nikto
      - name: Run Nikto Scan
        run: |
          sudo apt-get update && sudo apt-get install nikto -y
          nikto -h https://egundem.com -output nikto_report.txt

      - name: Upload Nikto report
        uses: actions/upload-artifact@v4
        with:
          name: nikto-report
          path: nikto_report.txt

      # Nuclei
      - name: Install Nuclei
        run: |
          curl -sL https://github.com/projectdiscovery/nuclei/releases/latest/download/nuclei_3.4.7_linux_64bit.tar.gz | tar xz
          sudo mv nuclei /usr/local/bin/

      - name: Run Nuclei Scan
        run: nuclei -u https://egundem.com -o nuclei_report.txt

      - name: Upload Nuclei report
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-report
          path: nuclei_report.txt

      # Trivy
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@v2
        with:
          scan-type: fs
          format: table
          output: trivy_report.txt
          severity: HIGH,CRITICAL

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy_report.txt

      # Example: Create GitHub Issue if alerts exist
      - name: Create Security Issue
        uses: peter-evans/create-issue-from-file@v4
        if: always()
        with:
          title: "Security Scan Alerts"
          content-file: trivy_report.txt
          labels: security, automated
