name: Security Scans

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  zapscan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run ZAP baseline scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'https://egundem.com/gundem'
          fail_action: false
          docker_name: 'ghcr.io/zaproxy/zaproxy'

      - name: Upload ZAP report artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap
          path: ./zap_report.html

  trivy_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs        # Dosya sistemi taraması
          scan-path: .         # Repo kök dizini
          format: table        # Konsolda tablo formatında çıktı
          exit-code: 1         # Vulnerability varsa workflow fail olur
          ignore-unfixed: false
