name: Security All Scans

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  trivy_scan:
    name: Trivy File System Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.55.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.55.0_Linux-64bit.deb || sudo apt-get install -f -y
          trivy --version

      - name: Run Trivy FS Scan
        run: |
          trivy fs . --exit-code 0 --severity HIGH,CRITICAL --format table --output trivy_report.txt

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy_report.txt

  nuclei_scan:
    name: Nuclei Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nuclei
        run: |
          sudo apt-get update && sudo apt-get install -y unzip wget
          wget https://github.com/projectdiscovery/nuclei/releases/latest/download/nuclei_3.4.7_linux_64bit.zip -O nuclei.zip
          unzip -o nuclei.zip
          sudo mv nuclei /usr/local/bin/
          nuclei -version

      - name: Run Nuclei Scan
        run: |
          nuclei -u https://egundem.com -severity critical,high -o nuclei_report.txt || true

      - name: Upload Nuclei Report
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-report
          path: nuclei_report.txt

  semgrep_scan:
    name: Semgrep Code Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: |
          pip install semgrep
          semgrep --version

      - name: Run Semgrep Scan
        run: |
          semgrep --config=auto --error --json > semgrep_report.json || true

      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep_report.json

  nikto_scan:
    name: Nikto Web Server Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nikto
        run: |
          sudo apt-get update
          sudo apt-get install -y nikto
          nikto -Version

      - name: Run Nikto Scan
        run: |
          nikto -h https://egundem.com > nikto_report.txt || true

      - name: Upload Nikto Report
        uses: actions/upload-artifact@v4
        with:
          name: nikto-report
          path: nikto_report.txt
