name: Trivy Security Scan

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update && sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.2_Linux-64bit.deb

      - name: Run Trivy FS scan (kod içi)
        run: trivy fs --exit-code 1 --severity HIGH,CRITICAL .

      # Docker imaj taraması istersen şunu da ekleyebilirsin:
      # - name: Run Trivy image scan
      #   run: trivy image your-docker-image
