name: Security All Scans

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  trivy_scan:
    name: Trivy File System Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Trivy CLI
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.65.1/trivy_0.65.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.65.1_Linux-64bit.deb
          trivy --version

      - name: Run Trivy FS Scan
        run: trivy fs . --severity HIGH,CRITICAL --exit-code 1 --format table --output trivy_report.txt

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy_report.txt

  semgrep_scan:
    name: Semgrep Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Semgrep Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto
          output: semgrep-results.json

      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-results.json

  nuclei_scan:
    name: Nuclei Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nuclei CLI
        run: |
          curl -sL https://github.com/projectdiscovery/nuclei/releases/download/v3.4.7/nuclei_3.4.7_linux_64bit.tar.gz -o nuclei.tar.gz
          tar -xzf nuclei.tar.gz
          sudo mv nuclei /usr/local/bin/
          nuclei -version

      - name: Run Nuclei Scan
        run: nuclei -t cves/ -o nuclei_report.txt -severity critical,high

      - name: Upload Nuclei Report
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-report
          path: nuclei_report.txt

  nikto_scan:
    name: Nikto Web Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nikto
        run: sudo apt-get update && sudo apt-get install nikto -y

      - name: Run Nikto Scan
        run: nikto -h https://egundem.com -output nikto_report.txt

      - name: Upload Nikto Report
        uses: actions/upload-artifact@v4
        with:
          name: nikto-report
          path: nikto_report.txt
