name: Security All Scans

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  security_scans:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # --------------------------
      # Trivy Container Tarama
      # --------------------------
      - name: Trivy Scan
        run: |
          sudo apt-get update && sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.65.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.65.0_Linux-64bit.deb
          trivy fs . --exit-code 0 --severity HIGH,CRITICAL --format table --output trivy_report.txt

      # --------------------------
      # Nuclei Tarama
      # --------------------------
      - name: Install Nuclei
        run: |
          curl -sL https://github.com/projectdiscovery/nuclei/releases/latest/download/nuclei_6.7.7_linux_64bit.tar.gz | tar xz
          sudo mv nuclei /usr/local/bin/
          nuclei -version

      - name: Run Nuclei Scan
        run: |
          nuclei -u https://egundem.com -o nuclei_report.txt

      # --------------------------
      # Nikto Tarama
      # --------------------------
      - name: Install Nikto
        run: sudo apt-get install nikto -y

      - name: Run Nikto Scan
        run: |
          nikto -h https://egundem.com -output nikto_report.txt

      # --------------------------
      # Semgrep Tarama
      # --------------------------
      - name: Install Semgrep
        uses: returntocorp/semgrep-action@v2
        with:
          config: "p/ci"
          output: semgrep_report.json

      # --------------------------
      # Upload All Reports
      # --------------------------
      - name: Upload Security Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            trivy_report.txt
            nuclei_report.txt
            nikto_report.txt
            semgrep_report.json
