name: Security All Scans

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  security_scans:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'https://egundem.com/gundem'
          fail_action: false
          docker_name: 'ghcr.io/zaproxy/zaproxy'

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: ./zap_report.html

      - name: Run Semgrep Scan
        run: npx semgrep --config=p/ci --json > semgrep_report.json || true

      - name: Upload Semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: ./semgrep_report.json

      - name: Run Trivy Scan
        run: |
          sudo apt-get update && sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.65.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.65.1_Linux-64bit.deb
          trivy fs . --exit-code 0 --severity HIGH,CRITICAL --format table --output trivy_report.txt

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: ./trivy_report.txt

      - name: Run Nikto Scan
        run: |
          sudo apt-get install nikto -y
          nikto -h https://egundem.com -output nikto_report.txt

      - name: Upload Nikto report
        uses: actions/upload-artifact@v4
        with:
          name: nikto-report
          path: ./nikto_report.txt

      - name: Run Nuclei Scan
        run: |
          curl -sL https://github.com/projectdiscovery/nuclei/releases/latest/download/nuclei_3.4.7_linux_64bit.tar.gz | tar xz
          ./nuclei -u https://egundem.com -o nuclei_report.txt

      - name: Upload Nuclei report
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-report
          path: ./nuclei_report.txt
