name: Security All Scans

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  trivy_scan:
    name: Trivy File System Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Trivy (Latest)
        run: |
          TRIVY_VERSION=$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep tag_name | cut -d '"' -f 4)
          wget https://github.com/aquasecurity/trivy/releases/download/${TRIVY_VERSION}/trivy_${TRIVY_VERSION#v}_Linux-64bit.deb
          sudo dpkg -i trivy_${TRIVY_VERSION#v}_Linux-64bit.deb || sudo apt-get install -f -y
          trivy --version

      - name: Run Trivy FS Scan
        run: |
          trivy fs . --exit-code 0 --severity HIGH,CRITICAL --format table --output trivy_report.txt

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy_report.txt

  nuclei_scan:
    name: Nuclei Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nuclei (Latest)
        run: |
          sudo apt-get update && sudo apt-get install -y unzip wget
          NUCLEI_VERSION=$(curl -s https://api.github.com/repos/projectdiscovery/nuclei/releases/latest | grep tag_name | cut -d '"' -f 4)
          wget https://github.com/projectdiscovery/nuclei/releases/download/${NUCLEI_VERSION}/nuclei_${NUCLEI_VERSION#v}_linux_amd64.zip -O nuclei.zip
          unzip -o nuclei.zip
          sudo mv nuclei /usr/local/bin/
          nuclei -version

      - name: Run Nuclei Scan
        run: |
          touch nuclei_report.txt
          nuclei -u https://egundem.com -t cves/ -o nuclei_report.txt -severity critical,high || true


      - name: Upload Nuclei Report
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-report
          path: nuclei_report.txt
          
  semgrep_scan:
    name: Semgrep Code Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: |
          pip install semgrep
          semgrep --version

      - name: Create Semgrep Ignore File
        run: |
          echo "node_modules/" > .semgrepignore
          echo "docs/" >> .semgrepignore
          echo "*.html" >> .semgrepignore

      - name: Run Semgrep Scan
        run: |
          semgrep --config=auto --exclude-dir=node_modules --exclude-dir=docs --exclude='*.html' \
          --severity=WARNING,ERROR --format=table > semgrep_report.txt || echo "No issues found or scan failed" > semgrep_report.txt

      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep_report.txt

  nikto_scan:
    name: Nikto Web Server Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nikto
        run: |
          sudo apt-get update
          sudo apt-get install -y nikto
          nikto -Version

      - name: Run Nikto Scan
        run: |
          nikto -h https://egundem.com > nikto_report.txt || true

      - name: Upload Nikto Report
        uses: actions/upload-artifact@v4
        with:
          name: nikto-report
          path: nikto_report.txt